function generateName() {
  var randomNumberFirstName = Math.floor((Math.random()*100)+0);
  var randomNumberMiddleName = Math.floor((Math.random()*100)+0);
  var boyNameChecked = document.getElementById('boy').checked;
  var girlNameChecked = document.getElementById('girl').checked;
  var firstNames;
  var middleNames;
  var lastName = document.getElementById('last-name').value;
  if (!lastName) {
    alert('You need to enter your last name!');
    return;
  }
  if (boyNameChecked) {
    firstNames = boyNames;
    middleNames = boyNames;
  } else if (girlNameChecked) {
    firstNames = girlNames;
    middleNames = girlNames;
  } else {
    alert('Please Select Boy Name or Girl Name!');
    return;
  }

  var firstName = firstNames[randomNumberFirstName];
  var middleName = middleNames[randomNumberMiddleName];

  while(firstName === middleName) {
    randomNumberMiddleName = Math.floor((Math.random()*100)+0);
    middleName = middleNames[randomNumberMiddleName];
  }
  var display = document.getElementById('baby-name');
  display.innerText = firstName + middleName + lastName;
}

function changeBackground (hexcode) {
  document.body.style.backgroundColor = hexcode;
  var display = document.getElementById('baby-name');
  display.innerText = '';
}

var girlNames = ['Sophia ',
'Emma ',
'Olivia ',
'Ava ',
'Mia ',
'Isabella ',
'Zoe ',
'Lily ',
'Emily ',
'Madison ',
'Amelia ',
'Riley ',
'Madelyn ',
'Charlotte ',
'Chloe ',
'Aubrey ',
'Aria ',
'Layla ',
'Avery ',
'Abigail ',
'Harper ',
'Kaylee ',
'Aaliyah ',
'Evelyn ',
'Adalyn ',
'Ella ',
'Arianna ',
'Hailey ',
'Ellie ',
'Nora ',
'Hannah ',
'Addison ',
'Mackenzie ',
'Brooklyn ',
'Scarlett ',
'Anna ',
'Mila ',
'Audrey ',
'Isabelle ',
'Elizabeth ',
'Leah ',
'Sarah ',
'Lillian ',
'Grace ',
'Natalie ',
'Kylie ',
'Lucy ',
'Makayla ',
'Maya ',
'Kaitlyn ',
'Victoria ',
'Elena ',
'Lila ',
'Maria ',
'Savannah ',
'Claire ',
'Penelope ',
'Alaina ',
'Violet ',
'Kennedy ',
'Gabriella ',
'Eliana ',
'Skyler ',
'Paisley ',
'Camilla ',
'Annabelle ',
'Adeline ',
'Stella ',
'Allison ',
'Alice ',
'Alyssa ',
'Liliana ',
'Reagan ',
'Charlie ',
'Callie ',
'Vivian ',
'Jocelyn ',
'Samantha ',
'Caroline ',
'Eleanor ',
'Julia ',
'Sophie ',
'Sadie ',
'Peyton ',
'Cora ',
'Juliana ',
'Eva ',
'Keira ',
'Hazel ',
'Kinsley ',
'Clara ',
'Katherine ',
'Alexandra ',
'Isla ',
'London ',
'Jordyn ',
'Kayla ',
'Bailey ',
'Emery ',
'Taylor '];

var boyNames = ['Jackson ',
'Aiden ',
'Liam ',
'Lucas ',
'Noah ',
'Mason ',
'Ethan ',
'Caden ',
'Logan ',
'Jacob ',
'Jayden ',
'Oliver ',
'Elijah ',
'Alexander ',
'Michael ',
'Carter ',
'James ',
'Caleb ',
'Benjamin ',
'Jack ',
'Luke ',
'Grayson ',
'William ',
'Ryan ',
'Connor ',
'Daniel ',
'Gabriel ',
'Owen ',
'Henry ',
'Matthew ',
'Isaac ',
'Wyatt ',
'Jayce ',
'Cameron ',
'Landon ',
'Nicholas ',
'Dylan ',
'Nathan ',
'Muhammad ',
'Sebastian ',
'Eli ',
'David ',
'Brayden ',
'Andrew ',
'Joshua ',
'Samuel ',
'Hunter ',
'Anthony ',
'Julian ',
'Dominic ',
'Christian ',
'Levi ',
'John ',
'Joseph ',
'Colton ',
'Isaiah ',
'Max ',
'Ian ',
'Evan ',
'Adam ',
'Thomas ',
'Gavin ',
'Aaron ',
'Jonathan ',
'Lincoln ',
'Christopher ',
'Miles ',
'Leo ',
'Nolan ',
'Parker ',
'Hudson ',
'Adrian ',
'Josiah ',
'Austin ',
'Cooper ',
'Carson ',
'Chase ',
'Tyler ',
'Jason ',
'Zachary ',
'Charlie ',
'Jeremiah ',
'Alex ',
'Jordan ',
'Mateo ',
'Tristan ',
'Asher ',
'Camden ',
'Xavier ',
'Easton ',
'Micah ',
'Cole ',
'Declan ',
'Nathaniel ',
'Brody ',
'Blake ',
'Ezra ',
'Damian ',
'Xander ',
'Elliot '];
